version: '3'

services:

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: nvmroot1357@!
    ports: 
      - 27017:27017
    networks: 
      - db

  books:
    container_name: books
    build:
      context: ..
      dockerfile: docker/prod/backend/Dockerfile
      args:
        name: book
    networks:
      - backend
      - db

  users:
    container_name: users
    build:
      context: ..
      dockerfile: docker/prod/backend/Dockerfile
      args:
        name: user
    networks:
      - backend
      - db

  preferences:
    container_name: preferences
    build:
      context: ..
      dockerfile: docker/prod/backend/Dockerfile
      args:
        name: preference
    networks:
      - backend
      - db

  gateway: 
    container_name: gateway
    build: 
      context: ..
      dockerfile: docker/prod/backend/Dockerfile
      args:
        name: gateway
    ports: 
      - 8080:8080
    networks: 
      - backend
      - frontend

  frontend:
    container_name: frontend
    build:
      context: ..
      dockerfile: docker/prod/frontend/Dockerfile
    ports:
      - 8000:80
    networks:
      - backend
      - db

networks:
  backend:
  frontend:
  db: