version: '3'

services:

  books:
    container_name: books
    build:
      context: ..
      dockerfile: docker/dev/all/Dockerfile
      args:
        name: book
    command: npm run dev
    volumes:
      - type: bind
        source: ../backend/book
        target: /opt/book
    networks:
      - backend
      - db

  users:
    container_name: users
    build:
      context: ..
      dockerfile: docker/dev/all/Dockerfile
      args:
        name: user
    command: npm run dev
    volumes:
      - type: bind
        source: ../backend/user
        target: /opt/user
    networks:
      - backend
      - db

  preferences:
    container_name: preferences
    build:
      context: ..
      dockerfile: docker/dev/all/Dockerfile
      args:
        name: preference
    command: npm run dev
    volumes:
      - type: bind
        source: ../backend/preference
        target: /opt/preference
    networks:
      - backend
      - db

  gateway: 
    container_name: gateway
    build: 
      context: ..
      dockerfile: docker/dev/all/Dockerfile
      args:
        name: gateway
    command: npm run dev
    volumes:
      - type: bind
        source: ../backend/gateway
        target: /opt/gateway
    ports: 
      - 8080:8080
    networks: 
      - backend
      - frontend

  frontend:
    container_name: frontend
    build:
      context: ..
      dockerfile: docker/dev/all/Dockerfile
      args:
        name: frontend
    command: npm run serve
    volumes:
      - ../frontend:/opt/frontend
    ports:
      - 8081:8081
    networks:
      - frontend

networks:
  backend:
  frontend:
  db: