const categories = [
 'antiques & collectibles',
 'architecture',
 'art',
 'bibles',
 'biography & autobiography',
 'body, mind & spirit',
 'business & economics',
 'comics & graphic novels',
 'computers',
 'cooking',
 'crafts & hobbies',
 'design',
 'drama',
 'education',
 'family & relationships',
 'fiction',
 'foreign language study',
 'games & activities',
 'gardening',
 'health & fitness',
 'history',
 'house & home',
 'humor',
 'juvenile fiction',
 'juvenile nonfiction',
 'language arts & disciplines',
 'law',
 'literary collections',
 'literary criticism',
 'mathematics',
 'medical',
 'music',
 'nature',
 'performing arts',
 'pets',
 'philosophy',
 'photography',
 'poetry',
 'political science',
 'psychology',
 'reference',
 'religion',
 'science',
 'self-help',
 'social science',
 'sports & recreation',
 'study aids',
 'technology & engineering',
 'transportation',
 'travel',
 'true crime',
 'young adult fiction',
 'young adult nonfiction',
];

 module.exports = {
  categories
};