# This is a basic workflow to help you get started with Actions

name: CI Users

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Run Mongo DB Users container
        run: |
            cd ./docker
            docker-compose -f docker-compose.dev.yml up --build -d mongodb-users

      # Runs a single command using the runners shell
      - name: Install User BE dependencies & run tests
        run: |
          cd ./backend/user
          echo "${{secrets.GOOGLE_SERVICE_ACCOUNT_KEY}}" > ./config/serviceAccountKey.json
          mv ./config/db.ci.config.js ./config/db.config.js
          npm i
          npm test
